import { createPigment as createPigmentInternal } from './core/factory.js';
import { BuilderPigment } from './core/builder.js';
import { default as chalk } from './core/chalk-default.js';
import {
  bold,
  dim,
  italic,
  underline,
  strikethrough,
  inverse,
  hidden,
  reset,
  black,
  red,
  green,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  blackBright,
  redBright,
  greenBright,
  yellowBright,
  blueBright,
  magentaBright,
  cyanBright,
  whiteBright,
  gray,
  grey,
  bgBlack,
  bgRed,
  bgGreen,
  bgYellow,
  bgBlue,
  bgMagenta,
  bgCyan,
  bgWhite,
  bgBlackBright,
  bgRedBright,
  bgGreenBright,
  bgYellowBright,
  bgBlueBright,
  bgMagentaBright,
  bgCyanBright,
  bgWhiteBright,
  bgGray,
  bgGrey,
  compose
} from './core/composer.js';
import type {
  PigmentOptions,
  ColorSupport,
  Styler,
  Pigment,
  Plugin,
  Kernel,
  PigmentKernel,
  PigmentContext,
  PigmentEvents,
  Style,
  StyleFunction,
  ThemePreset,
  BoxBorder,
  GradientPluginOptions,
  ThemePluginOptions,
  BoxPluginOptions,
  PigmentPluginOptions,
  Platform,
  SemanticPluginOptions,
  ThemePresetColors,
  BoxChars,
  KernelOptions,
  EventHandler
} from './types.js';

// Re-export from @oxog packages
export { createKernel } from '@oxog/plugin';
export type { MaybePromise, Unsubscribe } from '@oxog/types';
import { detectColorSupport, supportsColor, resetColorSupportCache } from './utils/color-support.js';
import {
  detectPlatform,
  isNode,
  isBrowser,
  isWindows,
  isCI,
  hasTTY
} from './utils/platform.js';
import { hexToRgb, validateHex } from './utils/hex-to-rgb.js';
import { hslToRgb } from './utils/hsl-to-rgb.js';
import { rgbToAnsi256 } from './utils/rgb-to-ansi256.js';
import * as plugins from './plugins/index.js';

const pigment = createPigmentInternal();
Object.assign(pigment, {
  bold,
  dim,
  italic,
  underline,
  strikethrough,
  inverse,
  hidden,
  reset,
  black,
  red,
  green,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  blackBright,
  redBright,
  greenBright,
  yellowBright,
  blueBright,
  magentaBright,
  cyanBright,
  whiteBright,
  gray,
  grey,
  bgBlack,
  bgRed,
  bgGreen,
  bgYellow,
  bgBlue,
  bgMagenta,
  bgCyan,
  bgWhite,
  bgBlackBright,
  bgRedBright,
  bgGreenBright,
  bgYellowBright,
  bgBlueBright,
  bgMagentaBright,
  bgCyanBright,
  bgWhiteBright,
  bgGray,
  bgGrey
});

export { pigment, createPigmentInternal as createPigment, BuilderPigment };

export {
  bold,
  dim,
  italic,
  underline,
  strikethrough,
  inverse,
  hidden,
  reset,
  black,
  red,
  green,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  blackBright,
  redBright,
  greenBright,
  yellowBright,
  blueBright,
  magentaBright,
  cyanBright,
  whiteBright,
  gray,
  grey,
  bgBlack,
  bgRed,
  bgGreen,
  bgYellow,
  bgBlue,
  bgMagenta,
  bgCyan,
  bgWhite,
  bgBlackBright,
  bgRedBright,
  bgGreenBright,
  bgYellowBright,
  bgBlueBright,
  bgMagentaBright,
  bgCyanBright,
  bgWhiteBright,
  bgGray,
  bgGrey,
  compose
};

export { plugins };

export {
  detectColorSupport,
  supportsColor,
  resetColorSupportCache,
  detectPlatform,
  isNode,
  isBrowser,
  isWindows,
  isCI,
  hasTTY,
  hexToRgb,
  validateHex,
  hslToRgb,
  rgbToAnsi256
};

export type {
  PigmentOptions,
  ColorSupport,
  Styler,
  Pigment,
  Plugin,
  Kernel,
  PigmentKernel,
  PigmentContext,
  PigmentEvents,
  Style,
  StyleFunction,
  ThemePreset,
  BoxBorder,
  GradientPluginOptions,
  ThemePluginOptions,
  BoxPluginOptions,
  PigmentPluginOptions,
  Platform,
  SemanticPluginOptions,
  ThemePresetColors,
  BoxChars,
  KernelOptions,
  EventHandler
};

export default chalk;
